### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by sixofife** [mykeels/20-questions#13]
"........Number 8 question (Combine Two Files). I don't seem to understand what the output should be. If only you can help out to edit the docs to contain what  you need the output to be.
Number 15 (Compound interest): Formular wasn't given for compound interest.
"

**Comment by mykeels** [comment]
The [file for Question 8](https://github.com/mykeels/20-questions/blob/master/programming/08-combine-two-files.md#sample-output) has been updated to include a Sample Output.
