### ISSUE TITLE
How can one Contribute

### ISSUE THREAD

**Issue by prondubuisi** [mykeels/20-questions#4]
Hello @mykeels good one, I am looking to contribute and would love pointers on where to add answers to the questions. i.e which folders. Maybe I can add a contributors guide and a PR template once you explain how this should work

**Comment by mykeels** [comment]
Thanks @prondubuisi ... I'm glad you like it, and are contributing.

See [this folder](https://github.com/mykeels/20-questions/tree/c-solutions/answers/C/%40mykeels) in the `c-solutions` branch. It contains my answers, written in c.

The folder format should be: 

```txt
answers/<Language|Framework>/<username>
```

e.g. 

```txt
answers/C/@mykeels
```

A contributors guide would be nice.
